### PR TITLE
fix/BR-32: Run npm update to fix 

### PR DESCRIPTION
**Pull request by phillip-elm**
No PR template here yet, we'll need to add one.

Pull security fixes for dependencies.

### CODE REVIEW

**Comment by deefactorial** [comment]
I'm getting failing tests when I run the `npm run test` for the Score tests. I've tried to add a .bitrank file, but the results are the same, are you able to run the tests ?

**Comment by phillip-elm** [comment]
Yeah - my tests pass. I'm using the test API, so I don't have a `.bitrank` in my env.

**Comment by deefactorial** [comment]
I'm not sure what caused the tests to fail, but after retrying `npm install` & `npm run test` it passes.

Your good to merge.

**Comment by deefactorial** [comment]
Accidentally closed.

**Pull request merged**
